name: Practice

on:
  push:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: '토큰 확인'
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: echo "token = $TOKEN"
