
name: TEST

on:
  pull_request:
    types: [ opened ]
    branches:    
      - 'fix/**'
      
jobs:
  approve:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    # if: ${{ github.event.requested_reviewer.login == 'approve-bot' }}
    env:
      GH_TOKEN: ${{ github.token }}
      NUMBER: ${{ github.event.number }}

    steps:
      - name: Auto Approve
        uses: hmarr/auto-approve-action@v2.2.1
